### ISSUE TITLE
Dependencies for global installation broken

### ISSUE THREAD

**Issue by ktomk** [dunkelfrosch/phpcoverfish#2]
Coverfish doesn't properly set the dependencies for the global installation. E.g. class `PHPUnit_Framework_TestCase` is not found.

**Comment by ktomk** [comment]
Workaround for this issue is:

    $ composer global require phpunit/phpunit:~4.7

**Comment by paterik** [comment]
thanx for this issue ... it will be fixed in upcoming version of this codebase by adding php-unit dependency inside "require" node of composer.json instead of "require-dev".

**Comment by ktomk** [comment]
Sounds good to me.
